### ISSUE TITLE
Feature: Raw request

### ISSUE THREAD

**Issue by vdun** [bcoles/ssrf_proxy#1]
Make it read from a raw request file similar to `sqlmap -r req.txt`. This option can substitute the options:
```
   -u, --url=URL          SSRF URL with 'xxURLxx' placeholder
       --method=METHOD    HTTP method (GET/HEAD/DELETE/POST/PUT)
                          (Default: GET)
       --post-data=DATA   HTTP post data
       --cookie=COOKIE    HTTP cookies (separated by ';')
       --user-agent=AGENT HTTP user-agent (Default: Mozilla/5.0)
```

**Comment by bcoles** [comment]
Hi @vdun 

This has been on the todo list for a while. I intend to do a new release of 0.0.4 soon. Unfortunately this functionality will need to be pushed back until 0.0.5.

**Comment by bcoles** [comment]
Hi @vdun

This is implemented - finally.

You can specify a HTTP request file with the `--file` argument.

The `--ssl` flag can be used to specify that the HTTP request should be sent over SSL/TLS.

The options you mentioned above (`method`, `post-data`, etc) can be used in combination with the `--file` option. In instances where there's overlap, the arguments overwrite the headers in the file.

I haven't written test cases, so there's probably a few bugs.

**Comment by bcoles** [comment]
Ok, so there is a bug here. Due to the way the HTTP request is parsed (WEBrick), a `Content-Length` header is required for requests containing a body. Additionally, the `Content-Length` header must be accurate.

For example, the following request file will fail to load due to missing `Content-Length` header:

```
POST / HTTP/1.1
Host: example.local

url=xxURLxx
```

This can be resolved by adding a `Content-Length` header which specifies the length of the body.

```
POST /file.ext HTTP
Host: example.local
Content-Length: 11

url=xxURLxx
```

Note: This is only required to force SSRF Proxy to load the file. The `Content-Length` will be updated to the appropriate value when sending requests.

There are no plans to resolve this issue yet.
